package com.rokid.alarm1.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.rokid.alarm1.beans.AlarmBean;

import com.rokid.alarm1.db.AlarmBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alarmBeanDaoConfig;

    private final AlarmBeanDao alarmBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alarmBeanDaoConfig = daoConfigMap.get(AlarmBeanDao.class).clone();
        alarmBeanDaoConfig.initIdentityScope(type);

        alarmBeanDao = new AlarmBeanDao(alarmBeanDaoConfig, this);

        registerDao(AlarmBean.class, alarmBeanDao);
    }
    
    public void clear() {
        alarmBeanDaoConfig.getIdentityScope().clear();
    }

    public AlarmBeanDao getAlarmBeanDao() {
        return alarmBeanDao;
    }

}
