package com.rokid.alarm1.beans;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALARM_BEAN".
 */
public class AlarmBean {

    private Long _id;
    private String year;
    private String month;
    private String day;
    private String hour;
    private String minute;
    private String startDate;
    private Boolean isRepeat;
    private Integer isRepeatUnit;
    private String dayZone;
    private Long showTime;
    private Boolean isWakeUpAlarm;

    public AlarmBean() {
    }

    public AlarmBean(Long _id) {
        this._id = _id;
    }

    public AlarmBean(Long _id, String year, String month, String day, String hour, String minute, String startDate, Boolean isRepeat, Integer isRepeatUnit, String dayZone, Long showTime, Boolean isWakeUpAlarm) {
        this._id = _id;
        this.year = year;
        this.month = month;
        this.day = day;
        this.hour = hour;
        this.minute = minute;
        this.startDate = startDate;
        this.isRepeat = isRepeat;
        this.isRepeatUnit = isRepeatUnit;
        this.dayZone = dayZone;
        this.showTime = showTime;
        this.isWakeUpAlarm = isWakeUpAlarm;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public String getDay() {
        return day;
    }

    public void setDay(String day) {
        this.day = day;
    }

    public String getHour() {
        return hour;
    }

    public void setHour(String hour) {
        this.hour = hour;
    }

    public String getMinute() {
        return minute;
    }

    public void setMinute(String minute) {
        this.minute = minute;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public Boolean getIsRepeat() {
        return isRepeat;
    }

    public void setIsRepeat(Boolean isRepeat) {
        this.isRepeat = isRepeat;
    }

    public Integer getIsRepeatUnit() {
        return isRepeatUnit;
    }

    public void setIsRepeatUnit(Integer isRepeatUnit) {
        this.isRepeatUnit = isRepeatUnit;
    }

    public String getDayZone() {
        return dayZone;
    }

    public void setDayZone(String dayZone) {
        this.dayZone = dayZone;
    }

    public Long getShowTime() {
        return showTime;
    }

    public void setShowTime(Long showTime) {
        this.showTime = showTime;
    }

    public Boolean getIsWakeUpAlarm() {
        return isWakeUpAlarm;
    }

    public void setIsWakeUpAlarm(Boolean isWakeUpAlarm) {
        this.isWakeUpAlarm = isWakeUpAlarm;
    }

}
